### ISSUE TITLE
Guidance on Writing profile.xml

### ISSUE THREAD

**Issue by hnktn** [I5UCC/VRCVoiceMeeterControl#1]
Hello,

I'm currently working on setting up a profile using XML and would appreciate some guidance. If there are any sample files or templates for a profile.xml, could you please share them? This would greatly help me understand the correct structure and syntax needed.

Thank you for your assistance.

Best regards,
Haruhisa

**Comment by I5UCC** [comment]
Hello!

You can generate profiles with Voicemeeter itself by going to `Menu>Save Settings...`
You can either get the syntax out of that if you want to change things manulally, or just set it up like you want and then just export it with that option!
![grafik](https://github.com/I5UCC/VRCMeeter/assets/43730681/f0442e46-52e8-4cd1-96c4-f408b088dc3f)

Hope that helps!
~ I5

**Comment by hnktn** [comment]
Thank you for explaining that so clearly!
